spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simpleBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    enabled: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace
